// Demo data for screenshot-ready dashboard
// Uses realistic service business names and data

const DEMO_BUSINESS_ID = "demo-client-001";

// ── Helpers ──

function daysAgo(n: number, hour = 10, minute = 30): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function futureDate(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

function pastDate(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

// ── Business Info ──

export const DEMO_BUSINESS = {
  name: "Garcia Plumbing & HVAC",
  ownerName: "Mike",
};

// ── Overview Metrics (basic + enhanced) ──

export const DEMO_OVERVIEW = {
  callsToday: 6,
  appointmentsThisWeek: 8,
  missedCallsSaved: 4,
  totalCalls: 142,
  // Revenue
  revenueThisMonth: 4200,
  revenueChange: 23,
  revenueSaved: 1800,
  missedCallsRecoveredCount: 4,
  costPerLead: 3.47,
  roiMultiple: 8.4,
  // Business
  businessName: "Garcia Plumbing & HVAC",
  // Weekly summary
  weeklySummary: {
    totalCalls: 23,
    appointmentsBooked: 8,
    estimatedRevenue: 3400,
    missedCallsRecovered: 4,
    avgCallDuration: 165,
    busiestHour: "Tuesday 2\u20133 PM",
    trendingService: "Water Heater Installation",
    topService: { name: "AC Repair", percentage: 42 },
    languageBreakdown: { en: 16, es: 7 },
  },
  // Activity feed
  activityFeed: [
    {
      id: "evt-01",
      time: daysAgo(0, 15, 36),
      type: "sms_sent",
      title: "Confirmation SMS sent",
      description: "Drain Cleaning booked for Wednesday 11:00 AM",
      person: "Sofia Martinez",
      language: "es",
    },
    {
      id: "evt-02",
      time: daysAgo(0, 15, 35),
      type: "call_completed",
      title: "Called about Drain Cleaning",
      description: "Booked appointment for Wednesday 11 AM. Has spring mailer coupon.",
      person: "Sofia Martinez",
      language: "es",
      value: 250,
    },
    {
      id: "evt-03",
      time: daysAgo(0, 14, 10),
      type: "call_completed",
      title: "Called to confirm appointment",
      description: "Water heater installation verified for tomorrow 9 AM.",
      person: "Mike Johnson",
      language: "en",
    },
    {
      id: "evt-04",
      time: daysAgo(0, 13, 22),
      type: "sms_sent",
      title: "Reschedule confirmation sent",
      description: "Drain Cleaning moved to Monday 10:00 AM",
      person: "Ana Rodriguez",
      language: "es",
    },
    {
      id: "evt-05",
      time: daysAgo(0, 13, 20),
      type: "call_completed",
      title: "Called to reschedule",
      description: "Drain cleaning moved from Friday to Monday 10 AM. Also asked about home inspection pricing.",
      person: "Ana Rodriguez",
      language: "es",
      value: 350,
    },
    {
      id: "evt-06",
      time: daysAgo(0, 11, 26),
      type: "appointment_booked",
      title: "Appointment booked",
      description: "Property Showing — Saturday 10:00 AM",
      person: "Robert Chen",
      recovered: true,
      value: 450,
    },
    {
      id: "evt-07",
      time: daysAgo(0, 11, 25),
      type: "sms_received",
      title: "Replied to follow-up",
      description: "\"I'd like to see the Oak Hill property. Is Saturday at 10 AM available?\"",
      person: "Robert Chen",
    },
    {
      id: "evt-08",
      time: daysAgo(0, 11, 6),
      type: "sms_sent",
      title: "Follow-up SMS sent",
      description: "Sent booking link and available time slots",
      person: "Robert Chen",
    },
    {
      id: "evt-09",
      time: daysAgo(0, 11, 5),
      type: "call_missed",
      title: "Missed call",
      description: "AI sent automatic follow-up text with booking link",
      person: "Robert Chen",
      recovered: true,
    },
    {
      id: "evt-10",
      time: daysAgo(0, 10, 43),
      type: "sms_sent",
      title: "Emergency confirmation sent",
      description: "Pipe leak repair confirmed for today 4:00 PM. Tech will call en route.",
      person: "James Wilson",
      language: "en",
    },
    {
      id: "evt-11",
      time: daysAgo(0, 10, 42),
      type: "call_completed",
      title: "Emergency — Pipe Leak",
      description: "Kitchen sink leaking. Same-day emergency tech dispatched for 4 PM.",
      person: "James Wilson",
      language: "en",
      value: 400,
      urgent: true,
    },
    {
      id: "evt-12",
      time: daysAgo(0, 9, 16),
      type: "sms_sent",
      title: "Confirmation SMS sent",
      description: "AC Repair confirmed for Thursday 2:00 PM",
      person: "Maria Garcia",
      language: "es",
    },
    {
      id: "evt-13",
      time: daysAgo(0, 9, 15),
      type: "call_completed",
      title: "Called about AC Repair",
      description: "Carrier unit, ~8 years old, stopped cooling. Booked Thursday 2 PM.",
      person: "Maria Garcia",
      language: "es",
      value: 350,
    },
  ],
  // Business insights
  insights: [
    { text: "Your busiest day is Tuesday \u2014 34% of weekly calls", icon: "calendar" },
    { text: "Average call duration is 2:45 \u2014 callers are highly engaged", icon: "clock" },
    { text: "3 leads asked about \"water heater installation\" this week", icon: "trending" },
    { text: "AC Repair is your #1 booked service (42% of appointments)", icon: "star" },
    { text: "After-hours calls are up 15% \u2014 your AI handles them all", icon: "moon" },
  ],
  // Bilingual stats
  bilingualStats: {
    spanishCalls: 7,
    totalCalls: 23,
    percentage: 30,
  },
  // Estimate pipeline
  estimatePipeline: {
    new: { count: 1, value: 0 },
    sent: { count: 1, value: 199 },
    follow_up: { count: 1, value: 3500 },
    won: { count: 1, value: 5800 },
    lost: { count: 1, value: 4200 },
    totalPipelineValue: 3699,
    wonThisMonth: { count: 1, value: 5800 },
  },
  // Customer insights
  customerInsights: {
    totalCustomers: 10,
    repeatCallers: 5,
    repeatRate: 50,
    newThisMonth: 3,
    topByCallCount: [
      { name: "Maria Garcia", phone: "+1 (512) 555-0147", totalCalls: 5 },
      { name: "Mike Johnson", phone: "+1 (512) 555-0502", totalCalls: 4 },
      { name: "Ana Rodriguez", phone: "+1 (512) 555-0421", totalCalls: 3 },
    ],
  },
};

// ── Call Transcripts ──

export const DEMO_TRANSCRIPTS: Record<
  string,
  Array<{ speaker: "ai" | "caller"; text: string }>
> = {
  "demo-call-01": [
    { speaker: "ai", text: "Thank you for calling Garcia Plumbing and HVAC. This is our AI assistant. How can I help you today?" },
    { speaker: "caller", text: "Hola, \u00bfhablan espa\u00f1ol?" },
    { speaker: "ai", text: "\u00a1S\u00ed, por supuesto! \u00bfEn qu\u00e9 puedo ayudarle hoy?" },
    { speaker: "caller", text: "Necesito que alguien revise mi aire acondicionado. Dej\u00f3 de enfriar ayer por la noche." },
    { speaker: "ai", text: "Lamento escuchar eso. Puedo programar una cita de reparaci\u00f3n. \u00bfQu\u00e9 marca y modelo tiene su unidad?" },
    { speaker: "caller", text: "Es un Carrier, creo que tiene como 8 a\u00f1os." },
    { speaker: "ai", text: "Perfecto. Tengo disponibilidad el jueves a las 2 de la tarde. \u00bfLe funciona ese horario?" },
    { speaker: "caller", text: "S\u00ed, el jueves est\u00e1 bien." },
    { speaker: "ai", text: "Excelente. Queda agendada su cita para reparaci\u00f3n de AC el jueves a las 2:00 PM. Le enviar\u00e9 un mensaje de confirmaci\u00f3n. \u00bfAlgo m\u00e1s?" },
    { speaker: "caller", text: "No, eso es todo. Gracias." },
    { speaker: "ai", text: "\u00a1De nada! Que tenga buen d\u00eda." },
  ],
  "demo-call-02": [
    { speaker: "ai", text: "Thank you for calling Garcia Plumbing and HVAC. How can I help you?" },
    { speaker: "caller", text: "Hi, I've got water dripping from under my kitchen sink. It's getting worse." },
    { speaker: "ai", text: "I'm sorry to hear that. It sounds like you might have a pipe leak. Is the water actively dripping right now?" },
    { speaker: "caller", text: "Yeah, I've got a bucket under it but it's filling up pretty fast." },
    { speaker: "ai", text: "I'd recommend we get a technician out to you today. I have an emergency slot available at 4 PM. Would that work?" },
    { speaker: "caller", text: "Yes, please. That would be great." },
    { speaker: "ai", text: "Perfect. I've scheduled an emergency pipe leak repair for today at 4:00 PM. In the meantime, if you can locate the shutoff valve under the sink, turning it off will help slow the leak." },
    { speaker: "caller", text: "Good idea, I'll do that. Thank you." },
    { speaker: "ai", text: "You're welcome! Our technician will call you when they're en route. I'll send you a confirmation text right now." },
  ],
  "demo-call-04": [
    { speaker: "ai", text: "Gracias por llamar a Garcia Plumbing and HVAC. \u00bfEn qu\u00e9 puedo ayudarle?" },
    { speaker: "caller", text: "Hola, necesito cambiar mi cita de limpieza de drenaje del viernes." },
    { speaker: "ai", text: "Por supuesto. Déjeme ver las opciones disponibles. \u00bfQu\u00e9 d\u00eda le funcionar\u00eda mejor?" },
    { speaker: "caller", text: "\u00bfTienen algo para el lunes?" },
    { speaker: "ai", text: "S\u00ed, tengo disponibilidad el lunes a las 10 de la ma\u00f1ana. \u00bfLe parece bien?" },
    { speaker: "caller", text: "Perfecto. Y tambi\u00e9n quer\u00eda preguntar, \u00bfcu\u00e1nto cuesta una inspecci\u00f3n completa de la casa?" },
    { speaker: "ai", text: "La inspecci\u00f3n completa de plomer\u00eda tiene un costo de $199. Incluye revisi\u00f3n de todas las tuber\u00edas, drenajes y calentador de agua. \u00bfLe gustar\u00eda programar una?" },
    { speaker: "caller", text: "D\u00e9jeme pensarlo. Por ahora solo el cambio de cita." },
    { speaker: "ai", text: "Entendido. Su cita de limpieza de drenaje queda reprogramada para el lunes a las 10:00 AM. Le enviar\u00e9 una confirmaci\u00f3n por texto." },
  ],
  "demo-call-06": [
    { speaker: "ai", text: "Gracias por llamar a Garcia Plumbing and HVAC. \u00bfC\u00f3mo puedo ayudarle?" },
    { speaker: "caller", text: "Hola, tengo el drenaje del ba\u00f1o tapado. El agua casi no baja." },
    { speaker: "ai", text: "Puedo programar una limpieza de drenaje. \u00bfCu\u00e1ndo le quedar\u00eda bien?" },
    { speaker: "caller", text: "\u00bfTienen algo para esta semana?" },
    { speaker: "ai", text: "S\u00ed, tengo disponibilidad el mi\u00e9rcoles a las 11 de la ma\u00f1ana. \u00bfLe funciona?" },
    { speaker: "caller", text: "S\u00ed, perfecto. Ah, y tengo un cup\u00f3n que me lleg\u00f3 por correo en la primavera." },
    { speaker: "ai", text: "\u00a1Excelente! Puede entreg\u00e1rselo al t\u00e9cnico cuando llegue. He anotado que tiene cup\u00f3n. Su cita queda para el mi\u00e9rcoles a las 11:00 AM." },
    { speaker: "caller", text: "Muchas gracias." },
  ],
  "demo-call-15": [
    { speaker: "ai", text: "Thank you for calling Garcia Plumbing and HVAC. How can I help you?" },
    { speaker: "caller", text: "Hi, I smell gas near my water heater. I'm not sure what to do." },
    { speaker: "ai", text: "I want you to stay calm. First, do not turn on any lights or create any sparks. Can you open the windows and doors nearest to the water heater?" },
    { speaker: "caller", text: "Okay, I'm opening the back door now." },
    { speaker: "ai", text: "Good. Is anyone else in the house?" },
    { speaker: "caller", text: "My husband and kids are here." },
    { speaker: "ai", text: "Please have everyone step outside to be safe. I'm dispatching an emergency technician to your location right now. They'll be there in about 20 minutes." },
    { speaker: "caller", text: "Thank you. We'll go outside." },
    { speaker: "ai", text: "You're doing the right thing. Our technician is on the way. I'll send you a text with the estimated arrival time. Stay outside until our tech confirms it's safe." },
  ],
};

// ── Missed Call Recovery Timelines ──

export const DEMO_RECOVERY_TIMELINES: Record<
  string,
  Array<{ time: string; event: string; detail: string; status: "missed" | "action" | "reply" | "recovered" }>
> = {
  "demo-call-03": [
    { time: daysAgo(0, 11, 5), event: "Call missed", detail: "Incoming call from Robert Chen", status: "missed" },
    { time: daysAgo(0, 11, 6), event: "AI follow-up sent", detail: "\"Hi Robert, we missed your call! Book online or reply with a time...\"", status: "action" },
    { time: daysAgo(0, 11, 25), event: "Client replied", detail: "\"I'd like to see the Oak Hill property. Is Saturday at 10 AM available?\"", status: "reply" },
    { time: daysAgo(0, 11, 26), event: "Appointment booked", detail: "Property Showing \u2014 Saturday 10:00 AM (est. $450)", status: "recovered" },
  ],
  "demo-call-07": [
    { time: daysAgo(1, 8, 45), event: "Call missed", detail: "Incoming call from David Thompson", status: "missed" },
    { time: daysAgo(1, 8, 46), event: "AI follow-up sent", detail: "\"Hi David, we missed your call. Openings at 9 AM and 2 PM...\"", status: "action" },
    { time: daysAgo(1, 9, 10), event: "Client replied", detail: "\"9 AM works. It's for a leaking shower head.\"", status: "reply" },
    { time: daysAgo(1, 9, 11), event: "Appointment booked", detail: "Shower Head Repair \u2014 Next day 9:00 AM (est. $200)", status: "recovered" },
  ],
  "demo-call-14": [
    { time: daysAgo(4, 12, 0), event: "Call missed", detail: "Incoming call from Kevin Wright", status: "missed" },
    { time: daysAgo(4, 12, 1), event: "AI follow-up sent", detail: "\"Hi Kevin, sorry we missed your call! Slots: Thu 10 AM, Fri 2 PM\"", status: "action" },
    { time: daysAgo(4, 12, 30), event: "No reply yet", detail: "Follow-up queued for tomorrow morning", status: "action" },
  ],
};

// ── Calls ──

export const DEMO_CALLS = [
  {
    id: "demo-call-01",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0147",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 185,
    language: "es",
    summary: "Maria called to schedule an AC repair for her home unit that stopped cooling. Appointment booked for Thursday at 2 PM. She mentioned the unit is a Carrier model, approximately 8 years old.",
    sentiment: "positive",
    createdAt: daysAgo(0, 9, 15),
    leadName: "Maria Garcia",
  },
  {
    id: "demo-call-02",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0238",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 142,
    language: "en",
    summary: "James called about a pipe leak in his kitchen. Urgent \u2014 water is dripping from under the sink. Scheduled same-day emergency visit for 4 PM today.",
    sentiment: "neutral",
    createdAt: daysAgo(0, 10, 42),
    leadName: "James Wilson",
  },
  {
    id: "demo-call-03",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0319",
    calledPhone: "+1 (512) 555-0100",
    status: "missed",
    duration: null,
    language: "en",
    summary: "Missed call \u2014 AI left voicemail offering callback. Caller later texted to book a showing for the Oak Hill property.",
    sentiment: "neutral",
    createdAt: daysAgo(0, 11, 5),
    leadName: "Robert Chen",
  },
  {
    id: "demo-call-04",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0421",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 210,
    language: "es",
    summary: "Ana called to reschedule her drain cleaning appointment from Friday to next Monday at 10 AM. Updated in calendar. She also asked about pricing for a full home inspection.",
    sentiment: "positive",
    createdAt: daysAgo(0, 13, 20),
    leadName: "Ana Rodriguez",
  },
  {
    id: "demo-call-05",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0502",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 95,
    language: "en",
    summary: "Mike called to confirm his water heater installation appointment for tomorrow. Confirmed 9 AM arrival window.",
    sentiment: "positive",
    createdAt: daysAgo(0, 14, 10),
    leadName: "Mike Johnson",
  },
  {
    id: "demo-call-06",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0618",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 165,
    language: "es",
    summary: "Sofia called about a clogged bathroom drain. Booked appointment for Wednesday at 11 AM. Mentioned she has a coupon from the spring mailer.",
    sentiment: "positive",
    createdAt: daysAgo(0, 15, 35),
    leadName: "Sofia Martinez",
  },
  {
    id: "demo-call-07",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0734",
    calledPhone: "+1 (512) 555-0100",
    status: "missed",
    duration: null,
    language: "en",
    summary: "Missed call during business hours. AI sent follow-up text with online booking link.",
    sentiment: "neutral",
    createdAt: daysAgo(1, 8, 45),
    leadName: "David Thompson",
  },
  {
    id: "demo-call-08",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0856",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 220,
    language: "en",
    summary: "Linda called for a quote on whole-home water filtration. Provided details about her well water setup. Follow-up estimate to be emailed.",
    sentiment: "positive",
    createdAt: daysAgo(1, 10, 15),
    leadName: "Linda Park",
  },
  {
    id: "demo-call-09",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0912",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 130,
    language: "es",
    summary: "Carlos asked about AC maintenance plans. Explained the annual service package and pricing. He said he'd discuss with his wife and call back.",
    sentiment: "neutral",
    createdAt: daysAgo(1, 14, 30),
    leadName: "Carlos Mendez",
  },
  {
    id: "demo-call-10",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1023",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 175,
    language: "en",
    summary: "Emily called about a running toilet in her guest bathroom. Diagnosed likely flapper valve issue over the phone. Booked repair for Friday 1 PM.",
    sentiment: "positive",
    createdAt: daysAgo(2, 9, 0),
    leadName: "Emily Davis",
  },
  {
    id: "demo-call-11",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1145",
    calledPhone: "+1 (512) 555-0100",
    status: "missed",
    duration: null,
    language: "en",
    summary: "Missed call \u2014 after-hours. AI informed caller of business hours and offered to schedule a callback for the morning.",
    sentiment: "neutral",
    createdAt: daysAgo(2, 19, 45),
    leadName: null,
  },
  {
    id: "demo-call-12",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1267",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 200,
    language: "en",
    summary: "Tom called requesting an estimate for re-piping his 1970s home. Discussed scope and timeline. Site visit scheduled for next week.",
    sentiment: "positive",
    createdAt: daysAgo(3, 11, 20),
    leadName: "Tom Bradley",
  },
  {
    id: "demo-call-13",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1389",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 88,
    language: "es",
    summary: "Rosa called to cancel her Friday appointment due to a scheduling conflict. Rescheduled to next Tuesday at 3 PM.",
    sentiment: "neutral",
    createdAt: daysAgo(3, 15, 10),
    leadName: "Rosa Flores",
  },
  {
    id: "demo-call-14",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1490",
    calledPhone: "+1 (512) 555-0100",
    status: "missed",
    duration: null,
    language: "en",
    summary: "Missed call \u2014 AI captured caller info and sent text with next available appointment slots.",
    sentiment: "neutral",
    createdAt: daysAgo(4, 12, 0),
    leadName: "Kevin Wright",
  },
  {
    id: "demo-call-15",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1501",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 155,
    language: "en",
    summary: "Sarah called about a gas smell near her water heater. Advised to open windows and evacuated. Emergency tech dispatched immediately.",
    sentiment: "negative",
    createdAt: daysAgo(5, 7, 30),
    leadName: "Sarah Kim",
  },
];

// ── Appointments ──

export const DEMO_APPOINTMENTS_UPCOMING = [
  {
    id: "demo-appt-01",
    service: "AC Repair",
    date: futureDate(1),
    time: "14:00",
    duration: 60,
    status: "confirmed",
    notes: "Carrier unit, ~8 years old, not cooling",
    createdAt: daysAgo(0, 9, 15),
    leadName: "Maria Garcia",
    leadPhone: "+1 (512) 555-0147",
  },
  {
    id: "demo-appt-02",
    service: "Pipe Leak Repair",
    date: futureDate(0),
    time: "16:00",
    duration: 45,
    status: "confirmed",
    notes: "Kitchen sink leak \u2014 urgent",
    createdAt: daysAgo(0, 10, 42),
    leadName: "James Wilson",
    leadPhone: "+1 (512) 555-0238",
  },
  {
    id: "demo-appt-03",
    service: "Property Showing",
    date: futureDate(2),
    time: "10:00",
    duration: 30,
    status: "confirmed",
    notes: "Oak Hill property showing",
    createdAt: daysAgo(0, 11, 30),
    leadName: "Robert Chen",
    leadPhone: "+1 (512) 555-0319",
  },
  {
    id: "demo-appt-04",
    service: "Drain Cleaning",
    date: futureDate(4),
    time: "10:00",
    duration: 60,
    status: "confirmed",
    notes: "Rescheduled from Friday",
    createdAt: daysAgo(0, 13, 20),
    leadName: "Ana Rodriguez",
    leadPhone: "+1 (512) 555-0421",
  },
  {
    id: "demo-appt-05",
    service: "Water Heater Install",
    date: futureDate(1),
    time: "09:00",
    duration: 120,
    status: "confirmed",
    notes: "50 gal tank replacement",
    createdAt: daysAgo(0, 14, 10),
    leadName: "Mike Johnson",
    leadPhone: "+1 (512) 555-0502",
  },
  {
    id: "demo-appt-06",
    service: "Drain Cleaning",
    date: futureDate(3),
    time: "11:00",
    duration: 45,
    status: "confirmed",
    notes: "Bathroom drain \u2014 has coupon from spring mailer",
    createdAt: daysAgo(0, 15, 35),
    leadName: "Sofia Martinez",
    leadPhone: "+1 (512) 555-0618",
  },
  {
    id: "demo-appt-07",
    service: "Toilet Repair",
    date: futureDate(2),
    time: "13:00",
    duration: 30,
    status: "confirmed",
    notes: "Running toilet, likely flapper valve",
    createdAt: daysAgo(2, 9, 0),
    leadName: "Emily Davis",
    leadPhone: "+1 (512) 555-1023",
  },
  {
    id: "demo-appt-08",
    service: "Re-piping Estimate",
    date: futureDate(5),
    time: "10:00",
    duration: 90,
    status: "confirmed",
    notes: "1970s home, full re-pipe evaluation",
    createdAt: daysAgo(3, 11, 20),
    leadName: "Tom Bradley",
    leadPhone: "+1 (512) 555-1267",
  },
];

export const DEMO_APPOINTMENTS_PAST = [
  {
    id: "demo-appt-p01",
    service: "AC Maintenance",
    date: pastDate(2),
    time: "09:00",
    duration: 60,
    status: "completed",
    notes: "Annual tune-up",
    createdAt: daysAgo(5),
    leadName: "Carlos Mendez",
    leadPhone: "+1 (512) 555-0912",
  },
  {
    id: "demo-appt-p02",
    service: "Pipe Inspection",
    date: pastDate(3),
    time: "14:00",
    duration: 45,
    status: "completed",
    notes: null,
    createdAt: daysAgo(6),
    leadName: "Linda Park",
    leadPhone: "+1 (512) 555-0856",
  },
  {
    id: "demo-appt-p03",
    service: "Faucet Replacement",
    date: pastDate(5),
    time: "11:00",
    duration: 60,
    status: "no_show",
    notes: "Client did not answer door",
    createdAt: daysAgo(8),
    leadName: "Kevin Wright",
    leadPhone: "+1 (512) 555-1490",
  },
  {
    id: "demo-appt-p04",
    service: "Water Heater Repair",
    date: pastDate(7),
    time: "08:00",
    duration: 90,
    status: "completed",
    notes: "Emergency gas smell dispatch",
    createdAt: daysAgo(8),
    leadName: "Sarah Kim",
    leadPhone: "+1 (512) 555-1501",
  },
  {
    id: "demo-appt-p05",
    service: "Drain Cleaning",
    date: pastDate(8),
    time: "15:00",
    duration: 45,
    status: "cancelled",
    notes: "Client rescheduled to next week",
    createdAt: daysAgo(10),
    leadName: "Rosa Flores",
    leadPhone: "+1 (512) 555-1389",
  },
];

// ── SMS Messages ──

export const DEMO_SMS = [
  {
    id: "demo-sms-01",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0147",
    body: "Hi Maria! Your AC Repair appointment is confirmed for Thursday at 2:00 PM. Reply CANCEL to cancel. \u2014 Calltide",
    templateType: "appointment_confirm",
    status: "delivered",
    createdAt: daysAgo(0, 9, 16),
  },
  {
    id: "demo-sms-02",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0238",
    body: "Hi James! Emergency pipe leak repair confirmed for today at 4:00 PM. Our tech will call when en route. \u2014 Calltide",
    templateType: "appointment_confirm",
    status: "delivered",
    createdAt: daysAgo(0, 10, 43),
  },
  {
    id: "demo-sms-03",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0319",
    body: "Hi Robert, we missed your call! Book online anytime at calltide.com/book or reply with a time that works for you. \u2014 Calltide",
    templateType: "missed_call_followup",
    status: "delivered",
    createdAt: daysAgo(0, 11, 6),
  },
  {
    id: "demo-sms-04",
    direction: "inbound",
    fromNumber: "+1 (512) 555-0319",
    toNumber: "+1 (512) 555-0100",
    body: "I'd like to see the Oak Hill property. Is Saturday at 10 AM available?",
    templateType: null,
    status: "delivered",
    createdAt: daysAgo(0, 11, 25),
  },
  {
    id: "demo-sms-05",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0421",
    body: "Hi Ana! Your Drain Cleaning appointment has been rescheduled to Monday at 10:00 AM. See you then! \u2014 Calltide",
    templateType: "appointment_reschedule",
    status: "delivered",
    createdAt: daysAgo(0, 13, 22),
  },
  {
    id: "demo-sms-06",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0618",
    body: "Hi Sofia! Your Drain Cleaning is booked for Wednesday at 11:00 AM. Don't forget your spring coupon! \u2014 Calltide",
    templateType: "appointment_confirm",
    status: "delivered",
    createdAt: daysAgo(0, 15, 36),
  },
  {
    id: "demo-sms-07",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0734",
    body: "Hi David, we missed your call this morning. We have openings tomorrow at 9 AM and 2 PM. Reply to book! \u2014 Calltide",
    templateType: "missed_call_followup",
    status: "delivered",
    createdAt: daysAgo(1, 8, 46),
  },
  {
    id: "demo-sms-08",
    direction: "inbound",
    fromNumber: "+1 (512) 555-0734",
    toNumber: "+1 (512) 555-0100",
    body: "9 AM works. It's for a leaking shower head.",
    templateType: null,
    status: "delivered",
    createdAt: daysAgo(1, 9, 10),
  },
  {
    id: "demo-sms-09",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-1023",
    body: "Hi Emily! Toilet repair booked for Friday at 1:00 PM. Our tech will bring replacement parts. \u2014 Calltide",
    templateType: "appointment_confirm",
    status: "delivered",
    createdAt: daysAgo(2, 9, 2),
  },
  {
    id: "demo-sms-10",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-1490",
    body: "Hi Kevin, sorry we missed your call! Here are our next available slots: Thu 10 AM, Fri 2 PM. Reply to book. \u2014 Calltide",
    templateType: "missed_call_followup",
    status: "delivered",
    createdAt: daysAgo(4, 12, 1),
  },
  {
    id: "demo-sms-11",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-1501",
    body: "URGENT: Gas smell reported. Emergency tech dispatched to your location. ETA 20 minutes. Do NOT use any flames. \u2014 Calltide",
    templateType: "emergency_dispatch",
    status: "delivered",
    createdAt: daysAgo(5, 7, 32),
  },
  {
    id: "demo-sms-12",
    direction: "inbound",
    fromNumber: "+1 (512) 555-1501",
    toNumber: "+1 (512) 555-0100",
    body: "Thank you, we've opened all the windows. Waiting for the technician.",
    templateType: null,
    status: "delivered",
    createdAt: daysAgo(5, 7, 35),
  },
  {
    id: "demo-sms-13",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-1145",
    body: "Hi! We missed your call. Book online at calltide.com/book or reply with a time. — Calltide",
    templateType: "missed_call_followup",
    status: "failed",
    createdAt: daysAgo(2, 19, 46),
  },
];

// ── CRM: Customers ──

export const DEMO_CUSTOMERS = [
  {
    id: "demo-cust-01",
    businessId: DEMO_BUSINESS_ID,
    phone: "+1 (512) 555-0147",
    name: "Maria Garcia",
    email: "maria.garcia@email.com",
    address: "1842 Oakwood Dr, San Antonio, TX",
    language: "es",
    tags: ["repeat", "spanish"],
    notes: "Prefers morning appointments. Has a Carrier AC unit, ~8 years old.",
    source: "inbound_call",
    totalCalls: 5,
    totalAppointments: 3,
    totalEstimates: 1,
    lastCallAt: daysAgo(0, 9, 15),
    firstCallAt: daysAgo(45),
    isRepeat: true,
    deletedAt: null,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(0, 9, 15),
  },
  {
    id: "demo-cust-02",
    businessId: DEMO_BUSINESS_ID,
    phone: "+1 (512) 555-0238",
    name: "James Wilson",
    email: "jwilson@gmail.com",
    address: "3310 Elm St, San Antonio, TX",
    language: "en",
    tags: ["emergency"],
    notes: "Had a pipe leak emergency. Kitchen sink under-cabinet area.",
    source: "inbound_call",
    totalCalls: 2,
    totalAppointments: 1,
    totalEstimates: 0,
    lastCallAt: daysAgo(0, 10, 42),
    firstCallAt: daysAgo(14),
    isRepeat: true,
    deletedAt: null,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(0, 10, 42),
  },
  {
    id: "demo-cust-03",
    businessId: DEMO_BUSINESS_ID,
    phone: "+1 (512) 555-0421",
    name: "Ana Rodriguez",
    email: null,
    address: null,
    language: "es",
    tags: ["spanish"],
    notes: "Asked about home inspection pricing. Rescheduled drain cleaning to Monday.",
    source: "inbound_call",
    totalCalls: 3,
    totalAppointments: 2,
    totalEstimates: 1,
    lastCallAt: daysAgo(0, 13, 20),
    firstCallAt: daysAgo(30),
    isRepeat: true,
    deletedAt: null,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(0, 13, 20),
  },
  {
    id: "demo-cust-04",
    businessId: DEMO_BUSINESS_ID,
    phone: "+1 (512) 555-0502",
    name: "Mike Johnson",
    email: "mikej@yahoo.com",
    address: "7501 Ridgeline Blvd, San Antonio, TX",
    language: "en",
    tags: [],
    notes: "50 gal tank replacement. Water heater install confirmed for tomorrow 9 AM.",
    source: "inbound_call",
    totalCalls: 4,
    totalAppointments: 2,
    totalEstimates: 0,
    lastCallAt: daysAgo(0, 14, 10),
    firstCallAt: daysAgo(60),
    isRepeat: true,
    deletedAt: null,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(0, 14, 10),
  },
  {
    id: "demo-cust-05",
    businessId: DEMO_BUSINESS_ID,
    phone: "+1 (512) 555-0618",
    name: "Sofia Martinez",
    email: "sofia.m@outlook.com",
    address: null,
    language: "es",
    tags: ["coupon", "spanish"],
    notes: "Has spring mailer coupon. Bathroom drain issue.",
    source: "inbound_call",
    totalCalls: 1,
    totalAppointments: 1,
    totalEstimates: 0,
    lastCallAt: daysAgo(0, 15, 35),
    firstCallAt: daysAgo(0, 15, 35),
    isRepeat: false,
    deletedAt: null,
    createdAt: daysAgo(0, 15, 35),
    updatedAt: daysAgo(0, 15, 35),
  },
  {
    id: "demo-cust-06",
    businessId: DEMO_BUSINESS_ID,
    phone: "+1 (512) 555-0856",
    name: "Linda Park",
    email: "linda.park@email.com",
    address: "2200 Stonebridge Ln, San Antonio, TX",
    language: "en",
    tags: ["high-value"],
    notes: "Interested in whole-home water filtration. Well water setup. Follow-up estimate needed.",
    source: "inbound_call",
    totalCalls: 2,
    totalAppointments: 1,
    totalEstimates: 1,
    lastCallAt: daysAgo(1, 10, 15),
    firstCallAt: daysAgo(20),
    isRepeat: true,
    deletedAt: null,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1, 10, 15),
  },
  {
    id: "demo-cust-07",
    businessId: DEMO_BUSINESS_ID,
    phone: "+1 (512) 555-1267",
    name: "Tom Bradley",
    email: "tom.bradley@email.com",
    address: "490 Heritage Way, San Antonio, TX",
    language: "en",
    tags: ["high-value"],
    notes: "1970s home re-piping. Full re-pipe evaluation site visit scheduled.",
    source: "inbound_call",
    totalCalls: 1,
    totalAppointments: 1,
    totalEstimates: 1,
    lastCallAt: daysAgo(3, 11, 20),
    firstCallAt: daysAgo(3, 11, 20),
    isRepeat: false,
    deletedAt: null,
    createdAt: daysAgo(3, 11, 20),
    updatedAt: daysAgo(3, 11, 20),
  },
  {
    id: "demo-cust-08",
    businessId: DEMO_BUSINESS_ID,
    phone: "+1 (512) 555-1501",
    name: "Sarah Kim",
    email: null,
    address: "1600 Maple Ave, San Antonio, TX",
    language: "en",
    tags: ["emergency"],
    notes: "Gas smell near water heater. Emergency dispatch. Family evacuated safely.",
    source: "inbound_call",
    totalCalls: 2,
    totalAppointments: 1,
    totalEstimates: 0,
    lastCallAt: daysAgo(5, 7, 30),
    firstCallAt: daysAgo(12),
    isRepeat: true,
    deletedAt: null,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(5, 7, 30),
  },
  {
    id: "demo-cust-09",
    businessId: DEMO_BUSINESS_ID,
    phone: "+1 (512) 555-0912",
    name: "Carlos Mendez",
    email: null,
    address: null,
    language: "es",
    tags: ["spanish"],
    notes: "Asked about AC maintenance plans. Will discuss with wife and call back.",
    source: "inbound_call",
    totalCalls: 1,
    totalAppointments: 1,
    totalEstimates: 0,
    lastCallAt: daysAgo(1, 14, 30),
    firstCallAt: daysAgo(1, 14, 30),
    isRepeat: false,
    deletedAt: null,
    createdAt: daysAgo(1, 14, 30),
    updatedAt: daysAgo(1, 14, 30),
  },
  {
    id: "demo-cust-10",
    businessId: DEMO_BUSINESS_ID,
    phone: "+1 (512) 555-1023",
    name: "Emily Davis",
    email: "emily.d@gmail.com",
    address: null,
    language: "en",
    tags: [],
    notes: "Running toilet in guest bathroom. Likely flapper valve issue.",
    source: "inbound_call",
    totalCalls: 1,
    totalAppointments: 1,
    totalEstimates: 0,
    lastCallAt: daysAgo(2, 9, 0),
    firstCallAt: daysAgo(2, 9, 0),
    isRepeat: false,
    deletedAt: null,
    createdAt: daysAgo(2, 9, 0),
    updatedAt: daysAgo(2, 9, 0),
  },
];

// ── CRM: Estimates ──

export const DEMO_ESTIMATES: Array<{
  id: string; businessId: string; customerId: string; customerName: string; customerPhone: string;
  callId: string | null; service: string; description: string; status: string; amount: number | null;
  followUpCount: number; lastFollowUpAt: string | null; nextFollowUpAt: string | null;
  wonAt: string | null; lostAt: string | null; lostReason: string | null; notes: string | null;
  createdAt: string; updatedAt: string;
}> = [
  {
    id: "demo-est-01",
    businessId: DEMO_BUSINESS_ID,
    customerId: "demo-cust-06",
    customerName: "Linda Park",
    customerPhone: "+1 (512) 555-0856",
    callId: "demo-call-08",
    service: "Whole-Home Water Filtration",
    description: "Well water setup. Requested quote for complete filtration system.",
    status: "follow_up",
    amount: 3500,
    followUpCount: 1,
    lastFollowUpAt: daysAgo(0, 10, 0),
    nextFollowUpAt: futureDate(2),
    wonAt: null,
    lostAt: null,
    lostReason: null,
    notes: "Sent initial quote by email. Following up.",
    createdAt: daysAgo(1, 10, 15),
    updatedAt: daysAgo(0, 10, 0),
  },
  {
    id: "demo-est-02",
    businessId: DEMO_BUSINESS_ID,
    customerId: "demo-cust-07",
    customerName: "Tom Bradley",
    customerPhone: "+1 (512) 555-1267",
    callId: "demo-call-12",
    service: "Whole-Home Re-Piping",
    description: "1970s home, full re-pipe evaluation. Discussed scope and timeline.",
    status: "new",
    amount: null,
    followUpCount: 0,
    lastFollowUpAt: null,
    nextFollowUpAt: futureDate(3),
    wonAt: null,
    lostAt: null,
    lostReason: null,
    notes: "Site visit scheduled for next week to assess scope.",
    createdAt: daysAgo(3, 11, 20),
    updatedAt: daysAgo(3, 11, 20),
  },
  {
    id: "demo-est-03",
    businessId: DEMO_BUSINESS_ID,
    customerId: "demo-cust-03",
    customerName: "Ana Rodriguez",
    customerPhone: "+1 (512) 555-0421",
    callId: "demo-call-04",
    service: "Home Plumbing Inspection",
    description: "Full home inspection of all pipes, drains, and water heater.",
    status: "sent",
    amount: 199,
    followUpCount: 0,
    lastFollowUpAt: null,
    nextFollowUpAt: futureDate(1),
    wonAt: null,
    lostAt: null,
    lostReason: null,
    notes: null,
    createdAt: daysAgo(0, 13, 20),
    updatedAt: daysAgo(0, 13, 20),
  },
  {
    id: "demo-est-04",
    businessId: DEMO_BUSINESS_ID,
    customerId: "demo-cust-01",
    customerName: "Maria Garcia",
    customerPhone: "+1 (512) 555-0147",
    callId: null,
    service: "AC System Replacement",
    description: "Carrier unit is 8+ years old. Discussed potential full system replacement.",
    status: "won",
    amount: 5800,
    followUpCount: 2,
    lastFollowUpAt: daysAgo(10),
    nextFollowUpAt: null,
    wonAt: daysAgo(7),
    lostAt: null,
    lostReason: null,
    notes: "Signed contract. Installation scheduled for next month.",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(7),
  },
  {
    id: "demo-est-05",
    businessId: DEMO_BUSINESS_ID,
    customerId: "demo-cust-04",
    customerName: "Mike Johnson",
    customerPhone: "+1 (512) 555-0502",
    callId: null,
    service: "Tankless Water Heater Upgrade",
    description: "Discussed upgrading from 50gal tank to tankless system.",
    status: "lost",
    amount: 4200,
    followUpCount: 3,
    lastFollowUpAt: daysAgo(15),
    nextFollowUpAt: null,
    wonAt: null,
    lostAt: daysAgo(12),
    lostReason: "went_with_competitor",
    notes: "Chose a competitor with lower pricing.",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(12),
  },
  {
    id: "demo-est-06",
    businessId: DEMO_BUSINESS_ID,
    customerId: "demo-cust-09",
    customerName: "Carlos Mendez",
    customerPhone: "+1 (512) 555-0912",
    callId: null,
    service: "AC Maintenance Plan",
    description: "Annual service package for AC system.",
    status: "expired",
    amount: 299,
    followUpCount: 3,
    lastFollowUpAt: daysAgo(32),
    nextFollowUpAt: null,
    wonAt: null,
    lostAt: null,
    lostReason: null,
    notes: "No response after 3 follow-ups. Auto-expired.",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(15),
  },
];

// ── CRM: Service Pricing ──

export const DEMO_PRICING = [
  {
    id: "demo-price-01",
    businessId: DEMO_BUSINESS_ID,
    serviceName: "AC Repair",
    priceMin: 89,
    priceMax: 350,
    unit: "per_job",
    description: "Diagnostic and repair of residential AC units",
    isActive: true,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: "demo-price-02",
    businessId: DEMO_BUSINESS_ID,
    serviceName: "Drain Cleaning",
    priceMin: 99,
    priceMax: 250,
    unit: "per_job",
    description: "Standard drain cleaning for kitchen and bathroom drains",
    isActive: true,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: "demo-price-03",
    businessId: DEMO_BUSINESS_ID,
    serviceName: "Water Heater Install",
    priceMin: 800,
    priceMax: 2500,
    unit: "per_job",
    description: "Tank and tankless water heater installation",
    isActive: true,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: "demo-price-04",
    businessId: DEMO_BUSINESS_ID,
    serviceName: "Pipe Leak Repair",
    priceMin: 150,
    priceMax: 600,
    unit: "per_job",
    description: "Emergency and standard pipe leak repair",
    isActive: true,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: "demo-price-05",
    businessId: DEMO_BUSINESS_ID,
    serviceName: "Home Plumbing Inspection",
    priceMin: 149,
    priceMax: 249,
    unit: "per_job",
    description: "Full inspection of pipes, drains, and water heater",
    isActive: true,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: "demo-price-06",
    businessId: DEMO_BUSINESS_ID,
    serviceName: "AC Maintenance",
    priceMin: 79,
    priceMax: 149,
    unit: "per_hour",
    description: "Annual tune-up and maintenance service",
    isActive: true,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
];

export { DEMO_BUSINESS_ID };
