// Demo data for screenshot-ready dashboard
// Matches DashboardMockup names and realistic service businesses

const DEMO_BUSINESS_ID = "demo-client-001";

// ── Helpers ──

function daysAgo(n: number, hour = 10, minute = 30): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function futureDate(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

function pastDate(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

// ── Overview Metrics ──

export const DEMO_OVERVIEW = {
  callsToday: 6,
  appointmentsThisWeek: 8,
  missedCallsSaved: 4,
  totalCalls: 142,
};

// ── Calls ──

export const DEMO_CALLS = [
  {
    id: "demo-call-01",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0147",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 185,
    language: "es",
    summary: "Maria called to schedule an AC repair for her home unit that stopped cooling. Appointment booked for Thursday at 2 PM. She mentioned the unit is a Carrier model, approximately 8 years old.",
    sentiment: "positive",
    createdAt: daysAgo(0, 9, 15),
    leadName: "Maria Garcia",
  },
  {
    id: "demo-call-02",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0238",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 142,
    language: "en",
    summary: "James called about a pipe leak in his kitchen. Urgent — water is dripping from under the sink. Scheduled same-day emergency visit for 4 PM today.",
    sentiment: "neutral",
    createdAt: daysAgo(0, 10, 42),
    leadName: "James Wilson",
  },
  {
    id: "demo-call-03",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0319",
    calledPhone: "+1 (512) 555-0100",
    status: "missed",
    duration: null,
    language: "en",
    summary: "Missed call — AI left voicemail offering callback. Caller later texted to book a showing for the Oak Hill property.",
    sentiment: "neutral",
    createdAt: daysAgo(0, 11, 5),
    leadName: "Robert Chen",
  },
  {
    id: "demo-call-04",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0421",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 210,
    language: "es",
    summary: "Ana called to reschedule her drain cleaning appointment from Friday to next Monday at 10 AM. Updated in calendar. She also asked about pricing for a full home inspection.",
    sentiment: "positive",
    createdAt: daysAgo(0, 13, 20),
    leadName: "Ana Rodriguez",
  },
  {
    id: "demo-call-05",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0502",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 95,
    language: "en",
    summary: "Mike called to confirm his water heater installation appointment for tomorrow. Confirmed 9 AM arrival window.",
    sentiment: "positive",
    createdAt: daysAgo(0, 14, 10),
    leadName: "Mike Johnson",
  },
  {
    id: "demo-call-06",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0618",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 165,
    language: "es",
    summary: "Sofia called about a clogged bathroom drain. Booked appointment for Wednesday at 11 AM. Mentioned she has a coupon from the spring mailer.",
    sentiment: "positive",
    createdAt: daysAgo(0, 15, 35),
    leadName: "Sofia Martinez",
  },
  {
    id: "demo-call-07",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0734",
    calledPhone: "+1 (512) 555-0100",
    status: "missed",
    duration: null,
    language: "en",
    summary: "Missed call during business hours. AI sent follow-up text with online booking link.",
    sentiment: "neutral",
    createdAt: daysAgo(1, 8, 45),
    leadName: "David Thompson",
  },
  {
    id: "demo-call-08",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0856",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 220,
    language: "en",
    summary: "Linda called for a quote on whole-home water filtration. Provided details about her well water setup. Follow-up estimate to be emailed.",
    sentiment: "positive",
    createdAt: daysAgo(1, 10, 15),
    leadName: "Linda Park",
  },
  {
    id: "demo-call-09",
    direction: "inbound",
    callerPhone: "+1 (512) 555-0912",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 130,
    language: "es",
    summary: "Carlos asked about AC maintenance plans. Explained the annual service package and pricing. He said he'd discuss with his wife and call back.",
    sentiment: "neutral",
    createdAt: daysAgo(1, 14, 30),
    leadName: "Carlos Mendez",
  },
  {
    id: "demo-call-10",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1023",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 175,
    language: "en",
    summary: "Emily called about a running toilet in her guest bathroom. Diagnosed likely flapper valve issue over the phone. Booked repair for Friday 1 PM.",
    sentiment: "positive",
    createdAt: daysAgo(2, 9, 0),
    leadName: "Emily Davis",
  },
  {
    id: "demo-call-11",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1145",
    calledPhone: "+1 (512) 555-0100",
    status: "missed",
    duration: null,
    language: "en",
    summary: "Missed call — after-hours. AI informed caller of business hours and offered to schedule a callback for the morning.",
    sentiment: "neutral",
    createdAt: daysAgo(2, 19, 45),
    leadName: null,
  },
  {
    id: "demo-call-12",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1267",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 200,
    language: "en",
    summary: "Tom called requesting an estimate for re-piping his 1970s home. Discussed scope and timeline. Site visit scheduled for next week.",
    sentiment: "positive",
    createdAt: daysAgo(3, 11, 20),
    leadName: "Tom Bradley",
  },
  {
    id: "demo-call-13",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1389",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 88,
    language: "es",
    summary: "Rosa called to cancel her Friday appointment due to a scheduling conflict. Rescheduled to next Tuesday at 3 PM.",
    sentiment: "neutral",
    createdAt: daysAgo(3, 15, 10),
    leadName: "Rosa Flores",
  },
  {
    id: "demo-call-14",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1490",
    calledPhone: "+1 (512) 555-0100",
    status: "missed",
    duration: null,
    language: "en",
    summary: "Missed call — AI captured caller info and sent text with next available appointment slots.",
    sentiment: "neutral",
    createdAt: daysAgo(4, 12, 0),
    leadName: "Kevin Wright",
  },
  {
    id: "demo-call-15",
    direction: "inbound",
    callerPhone: "+1 (512) 555-1501",
    calledPhone: "+1 (512) 555-0100",
    status: "completed",
    duration: 155,
    language: "en",
    summary: "Sarah called about a gas smell near her water heater. Advised to open windows and evacuated. Emergency tech dispatched immediately.",
    sentiment: "negative",
    createdAt: daysAgo(5, 7, 30),
    leadName: "Sarah Kim",
  },
];

// ── Appointments ──

export const DEMO_APPOINTMENTS_UPCOMING = [
  {
    id: "demo-appt-01",
    service: "AC Repair",
    date: futureDate(1),
    time: "14:00",
    duration: 60,
    status: "confirmed",
    notes: "Carrier unit, ~8 years old, not cooling",
    createdAt: daysAgo(0, 9, 15),
    leadName: "Maria Garcia",
    leadPhone: "+1 (512) 555-0147",
  },
  {
    id: "demo-appt-02",
    service: "Pipe Leak Repair",
    date: futureDate(0),
    time: "16:00",
    duration: 45,
    status: "confirmed",
    notes: "Kitchen sink leak — urgent",
    createdAt: daysAgo(0, 10, 42),
    leadName: "James Wilson",
    leadPhone: "+1 (512) 555-0238",
  },
  {
    id: "demo-appt-03",
    service: "Property Showing",
    date: futureDate(2),
    time: "10:00",
    duration: 30,
    status: "confirmed",
    notes: "Oak Hill property showing",
    createdAt: daysAgo(0, 11, 30),
    leadName: "Robert Chen",
    leadPhone: "+1 (512) 555-0319",
  },
  {
    id: "demo-appt-04",
    service: "Drain Cleaning",
    date: futureDate(4),
    time: "10:00",
    duration: 60,
    status: "confirmed",
    notes: "Rescheduled from Friday",
    createdAt: daysAgo(0, 13, 20),
    leadName: "Ana Rodriguez",
    leadPhone: "+1 (512) 555-0421",
  },
  {
    id: "demo-appt-05",
    service: "Water Heater Install",
    date: futureDate(1),
    time: "09:00",
    duration: 120,
    status: "confirmed",
    notes: "50 gal tank replacement",
    createdAt: daysAgo(0, 14, 10),
    leadName: "Mike Johnson",
    leadPhone: "+1 (512) 555-0502",
  },
  {
    id: "demo-appt-06",
    service: "Drain Cleaning",
    date: futureDate(3),
    time: "11:00",
    duration: 45,
    status: "confirmed",
    notes: "Bathroom drain — has coupon from spring mailer",
    createdAt: daysAgo(0, 15, 35),
    leadName: "Sofia Martinez",
    leadPhone: "+1 (512) 555-0618",
  },
  {
    id: "demo-appt-07",
    service: "Toilet Repair",
    date: futureDate(2),
    time: "13:00",
    duration: 30,
    status: "confirmed",
    notes: "Running toilet, likely flapper valve",
    createdAt: daysAgo(2, 9, 0),
    leadName: "Emily Davis",
    leadPhone: "+1 (512) 555-1023",
  },
  {
    id: "demo-appt-08",
    service: "Re-piping Estimate",
    date: futureDate(5),
    time: "10:00",
    duration: 90,
    status: "confirmed",
    notes: "1970s home, full re-pipe evaluation",
    createdAt: daysAgo(3, 11, 20),
    leadName: "Tom Bradley",
    leadPhone: "+1 (512) 555-1267",
  },
];

export const DEMO_APPOINTMENTS_PAST = [
  {
    id: "demo-appt-p01",
    service: "AC Maintenance",
    date: pastDate(2),
    time: "09:00",
    duration: 60,
    status: "completed",
    notes: "Annual tune-up",
    createdAt: daysAgo(5),
    leadName: "Carlos Mendez",
    leadPhone: "+1 (512) 555-0912",
  },
  {
    id: "demo-appt-p02",
    service: "Pipe Inspection",
    date: pastDate(3),
    time: "14:00",
    duration: 45,
    status: "completed",
    notes: null,
    createdAt: daysAgo(6),
    leadName: "Linda Park",
    leadPhone: "+1 (512) 555-0856",
  },
  {
    id: "demo-appt-p03",
    service: "Faucet Replacement",
    date: pastDate(5),
    time: "11:00",
    duration: 60,
    status: "no_show",
    notes: "Client did not answer door",
    createdAt: daysAgo(8),
    leadName: "Kevin Wright",
    leadPhone: "+1 (512) 555-1490",
  },
  {
    id: "demo-appt-p04",
    service: "Water Heater Repair",
    date: pastDate(7),
    time: "08:00",
    duration: 90,
    status: "completed",
    notes: "Emergency gas smell dispatch",
    createdAt: daysAgo(8),
    leadName: "Sarah Kim",
    leadPhone: "+1 (512) 555-1501",
  },
  {
    id: "demo-appt-p05",
    service: "Drain Cleaning",
    date: pastDate(8),
    time: "15:00",
    duration: 45,
    status: "cancelled",
    notes: "Client rescheduled to next week",
    createdAt: daysAgo(10),
    leadName: "Rosa Flores",
    leadPhone: "+1 (512) 555-1389",
  },
];

// ── SMS Messages ──

export const DEMO_SMS = [
  {
    id: "demo-sms-01",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0147",
    body: "Hi Maria! Your AC Repair appointment is confirmed for Thursday at 2:00 PM. Reply CANCEL to cancel. — Calltide",
    templateType: "appointment_confirm",
    status: "delivered",
    createdAt: daysAgo(0, 9, 16),
  },
  {
    id: "demo-sms-02",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0238",
    body: "Hi James! Emergency pipe leak repair confirmed for today at 4:00 PM. Our tech will call when en route. — Calltide",
    templateType: "appointment_confirm",
    status: "delivered",
    createdAt: daysAgo(0, 10, 43),
  },
  {
    id: "demo-sms-03",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0319",
    body: "Hi Robert, we missed your call! Book online anytime at calltide.com/book or reply with a time that works for you. — Calltide",
    templateType: "missed_call_followup",
    status: "delivered",
    createdAt: daysAgo(0, 11, 6),
  },
  {
    id: "demo-sms-04",
    direction: "inbound",
    fromNumber: "+1 (512) 555-0319",
    toNumber: "+1 (512) 555-0100",
    body: "I'd like to see the Oak Hill property. Is Saturday at 10 AM available?",
    templateType: null,
    status: "delivered",
    createdAt: daysAgo(0, 11, 25),
  },
  {
    id: "demo-sms-05",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0421",
    body: "Hi Ana! Your Drain Cleaning appointment has been rescheduled to Monday at 10:00 AM. See you then! — Calltide",
    templateType: "appointment_reschedule",
    status: "delivered",
    createdAt: daysAgo(0, 13, 22),
  },
  {
    id: "demo-sms-06",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0618",
    body: "Hi Sofia! Your Drain Cleaning is booked for Wednesday at 11:00 AM. Don't forget your spring coupon! — Calltide",
    templateType: "appointment_confirm",
    status: "delivered",
    createdAt: daysAgo(0, 15, 36),
  },
  {
    id: "demo-sms-07",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-0734",
    body: "Hi David, we missed your call this morning. We have openings tomorrow at 9 AM and 2 PM. Reply to book! — Calltide",
    templateType: "missed_call_followup",
    status: "delivered",
    createdAt: daysAgo(1, 8, 46),
  },
  {
    id: "demo-sms-08",
    direction: "inbound",
    fromNumber: "+1 (512) 555-0734",
    toNumber: "+1 (512) 555-0100",
    body: "9 AM works. It's for a leaking shower head.",
    templateType: null,
    status: "delivered",
    createdAt: daysAgo(1, 9, 10),
  },
  {
    id: "demo-sms-09",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-1023",
    body: "Hi Emily! Toilet repair booked for Friday at 1:00 PM. Our tech will bring replacement parts. — Calltide",
    templateType: "appointment_confirm",
    status: "delivered",
    createdAt: daysAgo(2, 9, 2),
  },
  {
    id: "demo-sms-10",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-1490",
    body: "Hi Kevin, sorry we missed your call! Here are our next available slots: Thu 10 AM, Fri 2 PM. Reply to book. — Calltide",
    templateType: "missed_call_followup",
    status: "delivered",
    createdAt: daysAgo(4, 12, 1),
  },
  {
    id: "demo-sms-11",
    direction: "outbound",
    fromNumber: "+1 (512) 555-0100",
    toNumber: "+1 (512) 555-1501",
    body: "URGENT: Gas smell reported. Emergency tech dispatched to your location. ETA 20 minutes. Do NOT use any flames. — Calltide",
    templateType: "emergency_dispatch",
    status: "delivered",
    createdAt: daysAgo(5, 7, 32),
  },
  {
    id: "demo-sms-12",
    direction: "inbound",
    fromNumber: "+1 (512) 555-1501",
    toNumber: "+1 (512) 555-0100",
    body: "Thank you, we've opened all the windows. Waiting for the technician.",
    templateType: null,
    status: "delivered",
    createdAt: daysAgo(5, 7, 35),
  },
];

export { DEMO_BUSINESS_ID };
