export const TRADE_PROFILES = {
  // ===== TIER 1: HIGHEST ROI — EMERGENCY-DRIVEN TRADES =====
  hvac: {
    label: "HVAC",
    tier: 1,
    avgServiceCall: 150,
    avgRepairJob: 400,
    avgInstallJob: 7500,
    avgJobValue: 350,
    callsPerDay: { small: 8, medium: 18, large: 35 },
    missedCallRate: 0.27,
    callerCallbackRate: 0.15,
    emergencyRate: 0.30,
    seasonalPeak: "Summer AC failures + winter heating emergencies",
    painPoints: [
      "After-hours emergencies (AC dies at 11 PM in July — that's a $5,000+ replacement if you answer)",
      "Seasonal call spikes overwhelm the front desk",
      "Spanish-speaking homeowners can't communicate the problem",
      "Techs in the field can't answer the office phone",
    ],
    commonServices: [
      "AC repair & installation",
      "Heating repair & installation",
      "Duct cleaning & sealing",
      "Maintenance plans & tune-ups",
      "Indoor air quality",
      "Thermostat installation",
    ],
    pricingBallparks: {
      "Service call / diagnostic": "$89-$150",
      "AC repair": "$150-$600",
      "AC installation": "$3,500-$12,000",
      "Furnace repair": "$150-$500",
      "Furnace installation": "$2,500-$8,000",
      "Duct cleaning": "$300-$500",
      "Maintenance tune-up": "$75-$200",
    },
    roiExample: {
      missedCallsPerDay: 5,
      avgJobValue: 350,
      monthlyLoss: 5 * 0.85 * 350 * 22,
      conservativeMonthlyLoss: 5 * 0.85 * 350 * 22 * 0.30,
    },
  },

  plumbing: {
    label: "Plumbing",
    tier: 1,
    avgServiceCall: 175,
    avgRepairJob: 400,
    avgInstallJob: 1800,
    avgJobValue: 275,
    callsPerDay: { small: 8, medium: 20, large: 40 },
    missedCallRate: 0.28,
    callerCallbackRate: 0.15,
    emergencyRate: 0.35,
    seasonalPeak: "Winter frozen pipes, spring storms, year-round emergencies",
    painPoints: [
      "Emergencies don't wait — burst pipe at 2 AM is a $1,000+ job that goes to whoever answers",
      "Solo operators physically can't answer while under a house",
      "High call volume: 15-25 calls/day for established shops",
      "Spanish-speaking households are 20%+ of the market in TX, FL, CA, AZ",
    ],
    commonServices: [
      "Drain cleaning & unclogging",
      "Water heater repair & installation",
      "Leak detection & repair",
      "Sewer line repair & replacement",
      "Fixture installation",
      "Pipe repair & repiping",
      "Gas line services",
      "Water treatment systems",
    ],
    pricingBallparks: {
      "Drain cleaning": "$150-$350",
      "Water heater repair": "$150-$700",
      "Water heater installation": "$800-$2,500",
      "Leak repair": "$150-$850",
      "Sewer line repair": "$1,000-$4,000",
      "Fixture installation": "$150-$400",
      "Emergency service call": "$200-$500",
    },
    roiExample: {
      missedCallsPerDay: 6,
      avgJobValue: 275,
      conservativeMonthlyLoss: 6 * 0.85 * 275 * 22 * 0.35,
    },
  },

  electrical: {
    label: "Electrical",
    tier: 1,
    avgServiceCall: 200,
    avgRepairJob: 400,
    avgInstallJob: 3000,
    avgJobValue: 350,
    callsPerDay: { small: 5, medium: 12, large: 25 },
    missedCallRate: 0.25,
    callerCallbackRate: 0.15,
    emergencyRate: 0.25,
    seasonalPeak: "Storm damage, summer overloads, remodel season",
    painPoints: [
      "Electrical emergencies are scary — sparking outlets, panel failures, storm damage",
      "Customers want someone NOW, not voicemail",
      "Estimate requests for remodels are high-value leads ($2K-$10K) that disappear fast",
      "Often running small crew, everyone's on a job site",
    ],
    commonServices: [
      "Panel upgrade & replacement",
      "Outlet & switch installation",
      "Whole-house rewiring",
      "Lighting installation",
      "Ceiling fan installation",
      "Generator installation",
      "EV charger installation",
      "Electrical troubleshooting",
    ],
    pricingBallparks: {
      "Service call / troubleshooting": "$100-$200",
      "Outlet or switch install": "$150-$300",
      "Panel upgrade": "$1,500-$3,000",
      "Whole-house rewiring": "$3,000-$10,000",
      "Ceiling fan install": "$150-$400",
      "Generator install": "$3,000-$6,000",
      "EV charger install": "$500-$2,000",
    },
    roiExample: {
      missedCallsPerDay: 3,
      avgJobValue: 350,
      conservativeMonthlyLoss: 3 * 0.85 * 350 * 22 * 0.30,
    },
  },

  // ===== TIER 2: HIGH ROI — HIGH TICKET TRADES =====
  roofing: {
    label: "Roofing",
    tier: 2,
    avgServiceCall: 300,
    avgRepairJob: 750,
    avgInstallJob: 12000,
    avgJobValue: 3000,
    callsPerDay: { small: 3, medium: 8, large: 20 },
    missedCallRate: 0.30,
    callerCallbackRate: 0.10,
    emergencyRate: 0.20,
    seasonalPeak: "After storms, spring/fall, insurance claim season",
    painPoints: [
      "Every missed call is potentially a $10K-$30K job going to the next Google result",
      "Storm season creates massive call spikes — 3x normal volume",
      "Insurance claim callers are high-value but impatient",
      "Estimate scheduling is the bottleneck — if you don't book the visit, you lose the job",
    ],
    commonServices: [
      "Roof inspection",
      "Shingle repair & replacement",
      "Full roof replacement",
      "Storm damage repair",
      "Gutter installation",
      "Roof leak repair",
      "Insurance claim assistance",
      "Commercial roofing",
    ],
    pricingBallparks: {
      "Roof inspection": "$100-$300",
      "Minor repair": "$200-$500",
      "Shingle replacement (partial)": "$500-$2,000",
      "Full roof replacement": "$8,000-$30,000+",
      "Storm damage repair": "$1,000-$5,000",
      "Gutter installation": "$1,000-$2,500",
    },
    roiExample: {
      missedCallsPerDay: 2,
      avgJobValue: 3000,
      conservativeMonthlyLoss: 2 * 0.90 * 3000 * 22 * 0.25,
    },
  },

  general_contractor: {
    label: "General Contracting",
    tier: 2,
    avgServiceCall: 0,
    avgRepairJob: 5000,
    avgInstallJob: 35000,
    avgJobValue: 15000,
    callsPerDay: { small: 3, medium: 8, large: 15 },
    missedCallRate: 0.35,
    callerCallbackRate: 0.10,
    emergencyRate: 0.05,
    seasonalPeak: "Spring through fall, year-round in warm climates",
    painPoints: [
      "Always on the job site — physically impossible to answer every call",
      "One missed remodel lead = $20K-$80K job gone",
      "Homeowners shopping for GCs call 3-5 companies — first to answer wins",
      "Estimate scheduling is critical — your calendar is your pipeline",
    ],
    commonServices: [
      "Kitchen remodel",
      "Bathroom remodel",
      "Room additions",
      "Whole-house renovation",
      "Deck & patio construction",
      "Basement finishing",
      "Siding & exterior",
      "Commercial build-out",
    ],
    pricingBallparks: {
      "Kitchen remodel": "$15,000-$50,000+",
      "Bathroom remodel": "$8,000-$30,000",
      "Room addition": "$20,000-$80,000+",
      "Deck construction": "$5,000-$20,000",
      "Basement finishing": "$15,000-$50,000",
    },
    roiExample: {
      missedCallsPerDay: 2,
      avgJobValue: 15000,
      conservativeMonthlyLoss: 2 * 0.90 * 15000 * 22 * 0.15,
    },
  },

  restoration: {
    label: "Restoration (Water/Fire/Mold)",
    tier: 2,
    avgServiceCall: 0,
    avgRepairJob: 3500,
    avgInstallJob: 12000,
    avgJobValue: 5000,
    callsPerDay: { small: 3, medium: 10, large: 25 },
    missedCallRate: 0.20,
    callerCallbackRate: 0.05,
    emergencyRate: 0.80,
    seasonalPeak: "Storm season, winter freeze, year-round emergencies",
    painPoints: [
      "EVERY call is an emergency — water is actively destroying their home RIGHT NOW",
      "The company that answers first gets the job, period",
      "Average insurance claim is $11K-$12.5K — missing one call costs more than a year of Maria",
      "24/7 coverage is non-negotiable in restoration",
    ],
    commonServices: [
      "Water damage restoration",
      "Fire damage restoration",
      "Mold remediation",
      "Storm damage repair",
      "Sewage cleanup",
      "Structural drying",
      "Insurance claim assistance",
      "Emergency board-up",
    ],
    pricingBallparks: {
      "Water damage mitigation": "$1,300-$6,000",
      "Fire damage restoration": "$10,000-$50,000+",
      "Mold remediation": "$1,500-$5,000",
      "Emergency response": "$500-$1,500 (initial)",
    },
    roiExample: {
      missedCallsPerDay: 2,
      avgJobValue: 5000,
      conservativeMonthlyLoss: 2 * 0.95 * 5000 * 22 * 0.50,
    },
  },

  // ===== TIER 3: SOLID ROI — SERVICE/MAINTENANCE TRADES =====
  landscaping: {
    label: "Landscaping",
    tier: 3,
    avgServiceCall: 0,
    avgRepairJob: 200,
    avgInstallJob: 8000,
    avgJobValue: 500,
    callsPerDay: { small: 5, medium: 12, large: 25 },
    missedCallRate: 0.30,
    callerCallbackRate: 0.15,
    emergencyRate: 0.05,
    seasonalPeak: "Spring through fall, year-round in warm climates",
    painPoints: [
      "Crew is in the field all day — nobody at the office to answer",
      "Hardscaping leads ($5K-$50K) are high-value and competitive",
      "Seasonal ramp-up creates call spikes in spring",
      "Bilingual crew but monolingual front desk loses Spanish-speaking clients",
    ],
    commonServices: [
      "Lawn care & mowing",
      "Landscape design & installation",
      "Hardscaping (patios, walkways, walls)",
      "Irrigation installation & repair",
      "Tree service & removal",
      "Seasonal cleanup",
      "Outdoor lighting",
      "Mulching & planting",
    ],
    pricingBallparks: {
      "Weekly lawn care": "$30-$80/visit",
      "Landscape design & install": "$3,000-$15,000",
      "Patio installation": "$5,000-$20,000",
      "Irrigation system": "$2,500-$5,000",
      "Tree removal": "$500-$2,000",
      "Seasonal cleanup": "$200-$500",
    },
    roiExample: {
      missedCallsPerDay: 4,
      avgJobValue: 500,
      conservativeMonthlyLoss: 4 * 0.85 * 500 * 22 * 0.25,
    },
  },

  pest_control: {
    label: "Pest Control",
    tier: 3,
    avgServiceCall: 175,
    avgRepairJob: 300,
    avgInstallJob: 1500,
    avgJobValue: 250,
    callsPerDay: { small: 8, medium: 20, large: 40 },
    missedCallRate: 0.25,
    callerCallbackRate: 0.15,
    emergencyRate: 0.15,
    seasonalPeak: "Spring/summer bug season, fall rodents",
    painPoints: [
      "High call volume, especially in season",
      "Customers are freaked out and want someone NOW (bed bugs, scorpions, rats)",
      "Recurring service plans are the real money — need to convert first call to subscription",
      "Competitive market — if you don't answer, the next guy on Google does",
    ],
    commonServices: [
      "General pest control",
      "Termite inspection & treatment",
      "Rodent control",
      "Bed bug treatment",
      "Mosquito control",
      "Wildlife removal",
      "Recurring maintenance plans",
    ],
    pricingBallparks: {
      "One-time treatment": "$150-$300",
      "Recurring plan": "$30-$70/month",
      "Termite treatment": "$500-$2,500",
      "Bed bug treatment": "$300-$1,500",
      "Rodent exclusion": "$200-$600",
    },
    roiExample: {
      missedCallsPerDay: 5,
      avgJobValue: 250,
      conservativeMonthlyLoss: 5 * 0.85 * 250 * 22 * 0.30,
    },
  },

  garage_door: {
    label: "Garage Door",
    tier: 3,
    avgServiceCall: 100,
    avgRepairJob: 300,
    avgInstallJob: 1200,
    avgJobValue: 350,
    callsPerDay: { small: 5, medium: 12, large: 25 },
    missedCallRate: 0.25,
    callerCallbackRate: 0.10,
    emergencyRate: 0.40,
    seasonalPeak: "Year-round, slight winter spike",
    painPoints: [
      "Garage door stuck = car trapped = urgent — they call the first company that answers",
      "Small crews, often just 1-2 techs — can't answer while on install",
      "Quick service turnaround means fast revenue if you answer",
    ],
    commonServices: [
      "Garage door repair",
      "Spring replacement",
      "Opener installation",
      "New door installation",
      "Emergency service",
      "Maintenance",
    ],
    pricingBallparks: {
      "Spring replacement": "$150-$350",
      "Opener repair": "$100-$250",
      "New opener install": "$250-$500",
      "New door installation": "$800-$2,500",
      "Emergency service": "$150-$300",
    },
    roiExample: {
      missedCallsPerDay: 3,
      avgJobValue: 350,
      conservativeMonthlyLoss: 3 * 0.90 * 350 * 22 * 0.35,
    },
  },

  other: {
    label: "Home Services",
    tier: 3,
    avgServiceCall: 150,
    avgRepairJob: 400,
    avgInstallJob: 2000,
    avgJobValue: 300,
    callsPerDay: { small: 5, medium: 15, large: 30 },
    missedCallRate: 0.27,
    callerCallbackRate: 0.15,
    emergencyRate: 0.20,
    seasonalPeak: "Varies",
    painPoints: [
      "Missing calls while on the job",
      "After-hours calls going to voicemail",
      "Need bilingual support for diverse customer base",
      "Can't afford a full-time receptionist",
    ],
    commonServices: [],
    pricingBallparks: {},
    roiExample: {
      missedCallsPerDay: 4,
      avgJobValue: 300,
      conservativeMonthlyLoss: 4 * 0.85 * 300 * 22 * 0.25,
    },
  },
} as const;

export type TradeType = keyof typeof TRADE_PROFILES;

/**
 * Calculate honest ROI for a specific trade.
 * Uses conservative assumptions — never overpromises.
 */
export function calculateROI(
  trade: TradeType,
  businessSize: "small" | "medium" | "large" = "small",
) {
  const profile = TRADE_PROFILES[trade];
  const callsPerDay = profile.callsPerDay[businessSize];
  const missedPerDay = Math.round(callsPerDay * profile.missedCallRate);
  const lostPerDay = Math.round(missedPerDay * (1 - profile.callerCallbackRate));
  const conversionRate = profile.emergencyRate > 0.3 ? 0.40 : 0.25;
  const lostJobsPerDay = lostPerDay * conversionRate;
  const dailyLoss = lostJobsPerDay * profile.avgJobValue;
  const monthlyLoss = dailyLoss * 22;
  const mariaPayback = Math.ceil(497 / profile.avgJobValue);

  return {
    callsPerDay,
    missedPerDay,
    lostForever: lostPerDay,
    estimatedMonthlyLoss: Math.round(monthlyLoss),
    mariaCost: 497,
    callsToPayForMaria: mariaPayback,
    roiMultiple: Math.round(monthlyLoss / 497),
    note: `Maria pays for herself after just ${mariaPayback} answered call${mariaPayback > 1 ? "s" : ""} that would have been missed.`,
  };
}
